# Generated by Django 4.0.1 on 2022-02-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/d2345cea-264e-4f75-ac80-1531406db1e4'),
        ),
    ]
