# Generated by Django 4.0.1 on 2022-02-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/3179e180-244d-423a-8e81-c721567727cc'),
        ),
    ]
